"""
Email Sender Module
Handles sending diagnostic reports via email.
"""

import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from typing import Dict, List, Optional, Tuple
from pathlib import Path
from dataclasses import dataclass
from enum import Enum


class EmailStatus(Enum):
    """Status of email sending operation."""
    PENDING = "pending"
    SENDING = "sending"
    SENT = "sent"
    FAILED = "failed"


@dataclass
class EmailConfig:
    """Configuration for email sending."""
    smtp_server: str
    smtp_port: int
    username: str
    password: str
    use_tls: bool = True
    use_ssl: bool = False


@dataclass
class EmailResult:
    """Result of email sending operation."""
    status: EmailStatus
    message_id: Optional[str] = None
    error_message: Optional[str] = None


class EmailSender:
    """Handles sending emails with attachments."""
    
    def __init__(self, config: Optional[EmailConfig] = None):
        self.config = config or self._get_default_config()
        self._test_connection()
    
    def _get_default_config(self) -> EmailConfig:
        """Get default email configuration."""
        # For now, return a placeholder configuration
        # In a real implementation, this would load from settings or environment
        return EmailConfig(
            smtp_server="smtp.gmail.com",
            smtp_port=587,
            username="your-email@gmail.com",
            password="your-app-password",
            use_tls=True
        )
    
    def _test_connection(self) -> bool:
        """Test the email connection."""
        try:
            # This is a placeholder - in a real implementation, you would test the connection
            return True
        except Exception:
            return False
    
    def send_report_email(
        self,
        recipient: str,
        subject: str,
        body: str,
        attachment_path: Optional[str] = None
    ) -> EmailResult:
        """Send a diagnostic report via email."""
        try:
            # Create message
            msg = MIMEMultipart()
            msg['From'] = self.config.username
            msg['To'] = recipient
            msg['Subject'] = subject
            
            # Add body
            msg.attach(MIMEText(body, 'plain'))
            
            # Add attachment if provided
            if attachment_path and Path(attachment_path).exists():
                self._add_attachment(msg, attachment_path)
            
            # Send email
            return self._send_email(msg)
            
        except Exception as e:
            return EmailResult(
                status=EmailStatus.FAILED,
                error_message=f"Failed to send email: {str(e)}"
            )
    
    def send_system_report(
        self,
        recipient: str,
        subject: str,
        report_path: str,
        system_summary: Optional[Dict] = None
    ) -> EmailResult:
        """Send a system diagnostic report via email."""
        try:
            # Create email body
            body = self._create_report_email_body(subject, system_summary)
            
            # Send email with attachment
            return self.send_report_email(recipient, subject, body, report_path)
            
        except Exception as e:
            return EmailResult(
                status=EmailStatus.FAILED,
                error_message=f"Failed to send system report: {str(e)}"
            )
    
    def _create_report_email_body(self, subject: str, system_summary: Optional[Dict]) -> str:
        """Create email body for system report."""
        body = f"""
Dear User,

Please find attached the diagnostic report: {subject}

"""
        
        if system_summary:
            body += f"""
System Summary:
- Operating System: {system_summary.get('os_name', 'Unknown')}
- CPU Usage: {system_summary.get('cpu_usage', 'Unknown')}%
- Memory Usage: {system_summary.get('memory_usage', 'Unknown')}%
- Disk Usage: {system_summary.get('disk_usage', 'Unknown')}%

"""
        
        body += """
This report was generated by the Inspector Diagnostic Utility.

Best regards,
Inspector Diagnostic Utility
        """
        
        return body
    
    def _add_attachment(self, msg: MIMEMultipart, file_path: str):
        """Add file attachment to email."""
        try:
            with open(file_path, "rb") as attachment:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(attachment.read())
            
            encoders.encode_base64(part)
            
            # Add header
            filename = Path(file_path).name
            part.add_header(
                'Content-Disposition',
                f'attachment; filename= {filename}'
            )
            
            msg.attach(part)
            
        except Exception as e:
            raise Exception(f"Failed to add attachment: {str(e)}")
    
    def _send_email(self, msg: MIMEMultipart) -> EmailResult:
        """Send email using configured SMTP settings."""
        try:
            # Create SMTP connection
            if self.config.use_ssl:
                server = smtplib.SMTP_SSL(self.config.smtp_server, self.config.smtp_port)
            else:
                server = smtplib.SMTP(self.config.smtp_server, self.config.smtp_port)
            
            # Start TLS if required
            if self.config.use_tls and not self.config.use_ssl:
                server.starttls(context=ssl.create_default_context())
            
            # Login
            server.login(self.config.username, self.config.password)
            
            # Send email
            text = msg.as_string()
            server.sendmail(self.config.username, msg['To'], text)
            server.quit()
            
            return EmailResult(
                status=EmailStatus.SENT,
                message_id=f"msg_{hash(text) % 1000000}"  # Simple message ID
            )
            
        except Exception as e:
            return EmailResult(
                status=EmailStatus.FAILED,
                error_message=f"SMTP error: {str(e)}"
            )
    
    def validate_email_config(self) -> Tuple[bool, str]:
        """Validate email configuration."""
        try:
            if not self.config.smtp_server:
                return False, "SMTP server is required"
            
            if not self.config.username:
                return False, "Username is required"
            
            if not self.config.password:
                return False, "Password is required"
            
            if self.config.smtp_port < 1 or self.config.smtp_port > 65535:
                return False, "SMTP port must be between 1 and 65535"
            
            # Test connection
            if not self._test_connection():
                return False, "Failed to connect to SMTP server"
            
            return True, "Email configuration is valid"
            
        except Exception as e:
            return False, f"Configuration validation failed: {str(e)}"
    
    def update_config(self, new_config: EmailConfig) -> bool:
        """Update email configuration."""
        try:
            self.config = new_config
            return self._test_connection()
        except Exception:
            return False


class EmailTemplateManager:
    """Manages email templates for different types of reports."""
    
    def __init__(self):
        self.templates = {
            'system_report': self._get_system_report_template(),
            'quick_scan': self._get_quick_scan_template(),
            'full_diagnostic': self._get_full_diagnostic_template()
        }
    
    def get_template(self, template_name: str) -> str:
        """Get email template by name."""
        return self.templates.get(template_name, self.templates['system_report'])
    
    def _get_system_report_template(self) -> str:
        """Get system report email template."""
        return """
Dear {recipient_name},

Please find attached the system diagnostic report: {report_title}

Report Details:
- Generated: {generation_date}
- System: {system_info}
- Scan Type: {scan_type}

Key Findings:
{key_findings}

If you have any questions about this report, please don't hesitate to contact us.

Best regards,
Inspector Diagnostic Utility
        """
    
    def _get_quick_scan_template(self) -> str:
        """Get quick scan email template."""
        return """
Dear {recipient_name},

Quick system scan completed successfully.

Scan Summary:
- Duration: {scan_duration}
- Issues Found: {issues_count}
- Recommendations: {recommendations_count}

Please review the attached report for detailed information.

Best regards,
Inspector Diagnostic Utility
        """
    
    def _get_full_diagnostic_template(self) -> str:
        """Get full diagnostic email template."""
        return """
Dear {recipient_name},

Full system diagnostic completed.

Diagnostic Summary:
- Scan Duration: {scan_duration}
- System Health: {health_score}%
- Critical Issues: {critical_issues}
- Warnings: {warnings}
- Recommendations: {recommendations}

The comprehensive report is attached for your review.

Best regards,
Inspector Diagnostic Utility
        """
    
    def format_template(self, template_name: str, **kwargs) -> str:
        """Format email template with provided parameters."""
        template = self.get_template(template_name)
        return template.format(**kwargs)


# Global instances for easy access
email_sender = EmailSender()
email_templates = EmailTemplateManager() 