#!/usr/bin/env python3
"""
Module Analysis Script
Analyzes all imports used by the Computer Inspector application.
"""

import ast
import os
import sys
from pathlib import Path
from typing import Set, List

def extract_imports_from_file(file_path: str) -> Set[str]:
    """Extract all imports from a Python file."""
    imports = set()
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        tree = ast.parse(content)
        
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    imports.add(alias.name)
            elif isinstance(node, ast.ImportFrom):
                module = node.module or ""
                for alias in node.names:
                    if module:
                        imports.add(f"{module}.{alias.name}")
                    else:
                        imports.add(alias.name)
                        
    except Exception as e:
        print(f"Error parsing {file_path}: {e}")
    
    return imports

def analyze_project_modules() -> Set[str]:
    """Analyze all modules used in the project."""
    all_imports = set()
    
    # Python files to analyze
    python_files = [
        "main.py",
        "core/system_info.py",
        "core/test_launcher.py", 
        "core/report_generator.py",
        "core/email_sender.py",
        "core/inspector_input.py",
        "ui/main_window.py",
        "ui/report_email_dialog.py",
        "gmail_config.py",
        "google_oauth_simple.py"
    ]
    
    for file_path in python_files:
        if os.path.exists(file_path):
            imports = extract_imports_from_file(file_path)
            all_imports.update(imports)
            print(f"📁 {file_path}: {len(imports)} imports")
        else:
            print(f"❌ {file_path}: File not found")
    
    return all_imports

def categorize_imports(imports: Set[str]) -> dict:
    """Categorize imports by type."""
    categories = {
        'standard_library': [],
        'third_party': [],
        'local_modules': [],
        'pyqt6_modules': []
    }
    
    # Standard library modules
    stdlib_modules = {
        'os', 'sys', 'platform', 'subprocess', 'time', 'datetime', 'pathlib',
        'json', 're', 'threading', 'concurrent.futures', 'smtplib', 'ssl',
        'email', 'dataclasses', 'enum', 'typing', 'collections', 'itertools',
        'functools', 'hashlib', 'base64', 'urllib', 'socket', 'select',
        'signal', 'tempfile', 'shutil', 'glob', 'fnmatch', 'stat', 'pwd',
        'grp', 'pipes', 'posix', 'nt', 'ntpath', 'posixpath'
    }
    
    for imp in sorted(imports):
        if imp.startswith('PyQt6'):
            categories['pyqt6_modules'].append(imp)
        elif imp.startswith('core.') or imp.startswith('ui.') or imp in ['gmail_config', 'google_oauth_simple']:
            categories['local_modules'].append(imp)
        elif imp in stdlib_modules or any(imp.startswith(std) for std in stdlib_modules):
            categories['standard_library'].append(imp)
        else:
            categories['third_party'].append(imp)
    
    return categories

def generate_pyinstaller_command(imports: Set[str]) -> str:
    """Generate PyInstaller command with all necessary hidden imports."""
    hidden_imports = []
    
    for imp in sorted(imports):
        if not imp.startswith('core.') and not imp.startswith('ui.'):
            hidden_imports.append(f'--hidden-import "{imp}"')
    
    return '\n    '.join(hidden_imports)

def main():
    """Main analysis function."""
    print("🔍 Analyzing Computer Inspector Application Modules")
    print("=" * 60)
    
    # Analyze all imports
    all_imports = analyze_project_modules()
    
    print(f"\n📊 Total unique imports found: {len(all_imports)}")
    
    # Categorize imports
    categories = categorize_imports(all_imports)
    
    print("\n📋 Import Categories:")
    print("-" * 30)
    
    for category, modules in categories.items():
        print(f"\n{category.upper()}:")
        for module in modules:
            print(f"  - {module}")
    
    # Generate PyInstaller command
    print("\n🔧 PyInstaller Hidden Imports:")
    print("-" * 30)
    pyinstaller_command = generate_pyinstaller_command(all_imports)
    print(pyinstaller_command)
    
    # Save to file
    with open('pyinstaller_imports.txt', 'w') as f:
        f.write("# PyInstaller hidden imports for Computer Inspector\n")
        f.write("# Generated by analyze_modules.py\n\n")
        f.write(pyinstaller_command)
    
    print(f"\n💾 PyInstaller imports saved to: pyinstaller_imports.txt")
    
    # Summary
    print(f"\n📈 Summary:")
    print(f"  - Standard Library: {len(categories['standard_library'])} modules")
    print(f"  - Third Party: {len(categories['third_party'])} modules")
    print(f"  - PyQt6: {len(categories['pyqt6_modules'])} modules")
    print(f"  - Local: {len(categories['local_modules'])} modules")
    print(f"  - Total: {len(all_imports)} modules")

if __name__ == "__main__":
    main() 